name: Greeting from AO Chon Long
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        NAME: AO Chon Long
      run: |
        echo $MY_VAR $NAME.
